feature/cli-runner
openmpf/openmpf-docker pull request #118
Opened 2020-09-08 16:21 UTC by brosenberg42

2021-03-26 02:25 UTC, jrobble requested changes
As discussed, I think we should put together some kind of architecture doc explaining our use of pybind. I created [this task](https://github.com/openmpf/openmpf/issues/1280) for later.

> Reviewed 20 of 26 files at r1, 4 of 4 files at r2, 8 of 8 files at r3, 21 of 21 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-:-MQnK2Em48O6FRRJHTAH:bnk8guc)* status: all files reviewed, 26 unresolved discussions (waiting on @brosenberg42)

___
*[components/docker-entrypoint.sh, line 41 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAo5au5h3qQjPNiOJd:-MNAo5au5h3qQjPNiOJe:b-cqhoy7) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/docker-entrypoint.sh#L41)):*
> ```Shell
> fi
> 
> if [ "$1" == -d ] || [ "$1" == --daemon ]; then
> ```

TODO: Test modes on command line.
___
*[components/docker-executor-entrypoint.py, line 323 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAwEDh7uzHOoAtX-O-:-MNAwEDh7uzHOoAtX-O0:b-4zlech) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/docker-executor-entrypoint.py#L323)):*
> ```Python
> 
>     component_log_full_path = os.path.join(log_dir, component_log_name)
>     if not os.path.exists(component_log_full_path):
> ```

TODO: Check that executor messages and component messages appear in the log available through the WFM UI and Kibana, and in terminal output when using CLI Runner.
___
*[components/cli_runner/Log4cxxConfig.xml, line 39 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAwqhyCg7Hn-Rj6b1g:-MNAwqhyCg7Hn-Rj6b1h:bre9383) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/Log4cxxConfig.xml#L39)):*
> ```XML
> 
>     <root>
>         <level value="${LOG_LEVEL}"/>
> ```

TODO: Try setting this and leaving it as default `INFO`.
___
*[components/cli_runner/mpf_cli_runner.py, line 104 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNQSoN81SfLHy5eV-fS:-MNQSoN81SfLHy5eV-fT:b-gs1t3a) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L104)):*
> ```Python
>             # component images.
>             import mpf_python_runner
>             self._component_handle = mpf_python_runner.PythonComponentHandle(descriptor)
> ```

Is there a reason the Python flow doesn't use `self._exit_stack.enter_context()`?
___
*[components/cli_runner/mpf_cli_runner.py, line 290 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNVCD-u1EnEjdfKFaQI:-MNVCD-vEv2xKOsUDJ8H:b-9izxvr) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L290)):*
> ```Python
>     def _get_media_metadata(cls, media_path: str, media_type: util.MediaType,
>                             media_metadata: Dict[str, str]) -> Dict[str, str]:
>         if media_type == util.MediaType.VIDEO and 'FPS' not in media_metadata:
> ```

TODO: Ensure all media types produce meaningful frame and time detection-level and track-level outputs.

TODO: Test that `ffprobe` and `ffmpeg` commands that produced different frame counts produce the same FPS.

---

We need to make it clear to the end user that HEIC files and crushed PNGs are not supported via the CLI Runner. Those will need to be transformed to supported file types prior to using the CLI Runner.
___
*[components/cli_runner/mpf_cli_runner.py, line 312 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNV9SaKER3VIy0ek0aZ:-MNV9SaL3ZjF2d5G9mE7:bj02g33) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L312)):*
> ```Python
> 
>         except subprocess.CalledProcessError as e:
>             raise RuntimeError(f'Unable to determine FPS with ffmpeg. Please set it on the '
> ```

In this error message I think you want to use "ffprobe" instead of "ffmpeg" to be more precise.
___
*[components/cli_runner/mpf_cli_runner.py, line 360 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNV0-V94MFoWGSz56jL:-MNV0-VA9WQ-nKqqLWh-:b-pkynij) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L360)):*
> ```Python
> 
>         log.warning('Media type argument missing. Attempting to guess file type...')
>         if 'video' in mime_type:
> ```

Do we want a case-insensitive check since `mime_type` could be user-specified?
___
*[components/cli_runner/mpf_cli_runner.py, line 483 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNQGRREAvAe6OKFno3g:-MNQGRREAvAe6OKFno3h:b-4bkkiw) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L483)):*
> ```Python
> 
> 
> def check_ld_lib_path(true_std_out, descriptor, mpf_home: pathlib.Path):
> ```

Where is this used?
___
*[components/cli_runner/mpf_cli_runner.py, line 572 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNQRMffEXcVtAPn7QJ0:-MNQRMffEXcVtAPn7QJ1:b-v30u13) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L572)):*
> ```Python
>         # Python doesn't use TRACE so we just log everything when TRACE is provided.
>         log_level = 'NOTSET'
>     log_format = '%(levelname)-5s [%(filename)s:%(lineno)d] - %(message)s'
> ```

Is this missing time (`asctime`)?

From `mpf_component_api.py`:

```
# Example log line: 2018-05-03 14:41:11,703 INFO  [test_component.py:44] - Logged message
LOG_MESSAGE_FORMAT = '%(asctime)s %(levelname)-5s [%(filename)s:%(lineno)d] - %(message)s'
```

From `PythonComponentHandle.cpp`:

```
py::arg("format")="%(asctime)s %(levelname)-5s [%(filename)s:%(lineno)d] - %(message)s",
```
___
*[components/cli_runner/mpf_cli_runner.py, line 619 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNV0agh4ry74cux8eC_:-MNV0agh4ry74cux8eCa:bpjcxuh) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L619)):*
> ```Python
>         '--media-metadata', '-M', action=ParsePropsAction, metavar='<metadata_name>=<value>',
>         help='Set a media metadata value. The argument should be the name of the metadata field '
>              'and its value separated by an "=" (e.g. "-P FPS=29.97"). '
> ```

Do you mean `(e.g. "-M FPS=29.97")` instead?
___
*[components/cli_runner/mpf_cli_runner.py, line 10 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MVZ9xfjED1tHmwv97zC:-MVZ9xfjED1tHmwv97zD:bx3baux) ([raw file](https://github.com/openmpf/openmpf-docker/blob/08ef8be90d5ec384d031e117f2ac4dae7160cc57/components/cli_runner/mpf_cli_runner.py#L10)):*
> ```Python
> # 52.227-14, Alt. IV (DEC 2007).                                            #
> #                                                                           #
> # Copyright 2020 The MITRE Corporation. All Rights Reserved.                #
> ```

Please update the copyright on the new files you added in this PR.
___
*[components/cli_runner/mpf_cli_runner_util.py, line 43 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MQnNzvj0ugBJDWcwjjx:-MQnNzvj0ugBJDWcwjjy:b-tzfb5w) ([raw file](https://github.com/openmpf/openmpf-docker/blob/3e2aa9d614193b6e9caad59957d64f2372e46808/components/cli_runner/mpf_cli_runner_util.py#L43)):*
> ```Python
> class ComponentHandle(Protocol):
>     """
>     Manages the lifetime of a language specific component.
> ```

Use hyphen: "language-specific"

Check for other uses.
___
*[components/cli_runner/mpf_cpp_runner.py, line 92 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MQnTec [...]

2021-03-26 16:05 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118)* status: 23 of 38 files reviewed, 26 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[components/cli_runner/mpf_cli_runner.py, line 104 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNQSoN81SfLHy5eV-fS:-MWilbxT9UkwdxPQ7wFh:bj5ld4q) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L104)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is there a reason the Python flow doesn't use `self._exit_stack.enter_context()`?
</blockquote></details>

CppComponentHandle is a context manager because C++ components have a `.Close()` method that needs to be called when we are done with the component. Python components don't have a `close` method or equivalent, so there is no reason for PythonComponentHandle to be a context manager.
___
*[components/cli_runner/mpf_cli_runner.py, line 290 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNVCD-u1EnEjdfKFaQI:-MWjEGA1AY5Xkpdi_eb-:bfp40o4) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L290)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

TODO: Ensure all media types produce meaningful frame and time detection-level and track-level outputs.

TODO: Test that `ffprobe` and `ffmpeg` commands that produced different frame counts produce the same FPS.

---

We need to make it clear to the end user that HEIC files and crushed PNGs are not supported via the CLI Runner. Those will need to be transformed to supported file types prior to using the CLI Runner.
</blockquote></details>

How? Where?
___
*[components/cli_runner/mpf_cli_runner.py, line 312 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNV9SaKER3VIy0ek0aZ:-MWinGSQ701MYm5URRoQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L312)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In this error message I think you want to use "ffprobe" instead of "ffmpeg" to be more precise.
</blockquote></details>

Done.
___
*[components/cli_runner/mpf_cli_runner.py, line 360 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNV0-V94MFoWGSz56jL:-MWinw0l5mxP1s3cEtg6:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L360)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do we want a case-insensitive check since `mime_type` could be user-specified?
</blockquote></details>

Done.
___
*[components/cli_runner/mpf_cli_runner.py, line 483 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNQGRREAvAe6OKFno3g:-MWio2_E6R-F9vu015ZS:b-myitk7) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L483)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Where is this used?
</blockquote></details>

It's no longer used
___
*[components/cli_runner/mpf_cli_runner.py, line 572 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNQRMffEXcVtAPn7QJ0:-MWioBoH51o8JvxLzxYD:b-1h1a6d) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L572)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this missing time (`asctime`)?

From `mpf_component_api.py`:

```
# Example log line: 2018-05-03 14:41:11,703 INFO  [test_component.py:44] - Logged message
LOG_MESSAGE_FORMAT = '%(asctime)s %(levelname)-5s [%(filename)s:%(lineno)d] - %(message)s'
```

From `PythonComponentHandle.cpp`:

```
py::arg("format")="%(asctime)s %(levelname)-5s [%(filename)s:%(lineno)d] - %(message)s",
```
</blockquote></details>

I intentionally tried to make the log messages shorter for the cli runner. Typically, command line tools don't output information formatted like log lines, but I still felt like it was useful to know where a message came from so that is why I included filename and lineno. I also use logging so that the verbosity can be easily controlled.

The time is useful when you are going through log files for component services that are running continuously. In the CLI runnner case, the users are running single pieces of media through at a time, so they already have an idea of when they ran the command. Having extremely long lines is acceptable in a log file, but unexpected for console output.
___
*[components/cli_runner/mpf_cli_runner.py, line 619 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNV0agh4ry74cux8eC_:-MWiq54g58LnElB4runu:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L619)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you mean `(e.g. "-M FPS=29.97")` instead?
</blockquote></details>

Done.
___
*[components/cli_runner/mpf_cli_runner.py, line 10 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MVZ9xfjED1tHmwv97zC:-MWjDHWe2NZ9Nu0AGRSJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/08ef8be90d5ec384d031e117f2ac4dae7160cc57/components/cli_runner/mpf_cli_runner.py#L10)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the copyright on the new files you added in this PR.
</blockquote></details>

Done.
___
*[components/cli_runner/mpf_python_runner.py, line 54 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MQnVizZEmFgOJr2QcCL:-MWiqyEZ5ZDzmaGOTYtS:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/3e2aa9d614193b6e9caad59957d64f2372e46808/components/cli_runner/mpf_python_runner.py#L54)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Since you provide an incorrect example below, please provide a correct example here for completeness and clarity, such as:

```
'mpf.exported_component': 'component = my_module:MyComponentClass'
```
</blockquote></details>

Done.
___
*[components/cli_runner/README.md, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAf5ooE1XlfcRmhwBZ:-MWjDpgzA5g4ipxT-oJx:b-q8htm3) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/README.md#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please link to this README from the top-level opempf-docker README just so that it gets better visibility. 

Also, I propose linking to it from the User Guide in the github.io page since this feature presents an entirely new and different way to use OpenMPF apart from the web UI. I left a comment on the github.io PR.
</blockquote></details>

Where? What should it say?
___
*[components/cli_runner/README.md, line 10 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAtNiN62ZxSW9Or5k2:-MWj3itm67Fau-cTitdM:b-bzx61l) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/README.md#L10)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update this README to:
- Mention optional `--verbose` argument
- Mention optional `--pretty` and `--brief` arguments for JSON output
- Provide media metadata example
- Provide video example that uses `--begin` and `--end`
</blockquote></details>

Having the command line argument documentation in the code itself is bett [...]

2021-03-26 16:44 UTC, brosenberg42 commented
___
*[components/cli_runner/mpf_cli_runner.py, line 290 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNVCD-u1EnEjdfKFaQI:-MWjPZaT9Qg1KgV1FR_N:b2ht7pe) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L290)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

How? Where?
</blockquote></details>

Thinking about this more, a user shouldn't be surprised that all possible media types aren't supported. What happens if a component does happen to support one of those formats?


<!-- Sent from Reviewable.io -->

2021-03-26 21:42 UTC, jrobble requested changes
> Reviewed 15 of 15 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118)* status: all files reviewed, 9 unresolved discussions (waiting on @brosenberg42)

___
*[components/cli_runner/mpf_cli_runner.py, line 290 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNVCD-u1EnEjdfKFaQI:-MWk3DQsErDaQgl1iq-3:b-l43juw) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L290)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Thinking about this more, a user shouldn't be surprised that all possible media types aren't supported. What happens if a component does happen to support one of those formats?
</blockquote></details>

I'm just saying we should give end users a heads up by chat, voice, or email that the CLI Runner doesn't do the same conversion as the WFM. It shouldn't come as a surprise, but best to tell them to make sure.
___
*[components/cli_runner/mpf_cli_runner.py, line 572 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNQRMffEXcVtAPn7QJ0:-MWkA94n2FhLWwB5btWX:bbusfsj) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/mpf_cli_runner.py#L572)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I intentionally tried to make the log messages shorter for the cli runner. Typically, command line tools don't output information formatted like log lines, but I still felt like it was useful to know where a message came from so that is why I included filename and lineno. I also use logging so that the verbosity can be easily controlled.

The time is useful when you are going through log files for component services that are running continuously. In the CLI runnner case, the users are running single pieces of media through at a time, so they already have an idea of when they ran the command. Having extremely long lines is acceptable in a log file, but unexpected for console output.
</blockquote></details>

Ok. I'm thinking about Azure components that can take a while because they are waiting on an external server. Log times could be helpful, but to your point, most command line applications don't output timestamps. We can add it in later if users want it.

In general, I find log times most helpful to understand how long each stage of a pipeline takes. Currently, the CLI Runner only performs one action, so a user can use `time` on the command line to see how long it takes.
___
*[components/cli_runner/README.md, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAf5ooE1XlfcRmhwBZ:-MWkCNFA9DLe96mfJMwz:b-n3gqf8) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/README.md#L1)):*
Thinking about this more. How about we move `openmpf-docker/components/cli_runner/README.md` to the top level so it becomes `openmpf-docker/CLI_RUNNER.md`? 

Then add an brief "(Optional) CLI Runner" section to `openmpf-docker/README.md` underneath "(Optional) Docker Swarm Deployment" that links to `CLI_RUNNER.md`. Talk about the motivation and what it does. You can reuse this line:

> The OpenMPF Command Line Runner (CLI runner) allows users to run jobs with a single componen without the Workflow Manager.

The section will be similar in length to the "(Optional) Docker Swarm Deployment" section. Mention that it does not depend on a `docker-compose.yml` file and only runs one container by itself.

---

I know we have `README.md` files for the executors and things in their sub-directories. I think that's fine since developers will be diving down into the source code. Normal users may only look at what's at the top level. 
___
*[components/cli_runner/README.md, line 10 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAtNiN62ZxSW9Or5k2:-MWkROJi4SG9qv0c0-Vz:btm3d9d) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/README.md#L10)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Having the command line argument documentation in the code itself is better than putting it here. Duplicating it here isn't particularly useful and just adds management burden. A user could also be looking at the documentation for a different branch from the version of the Docker image they have.  
</blockquote></details>

Sure. What you have now is fine. I think that the media metadata example is most important. In general, I would imagine that most users would run complete video files through.
___
*[components/cpp_executor/Dockerfile, line 98 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAvQnM0qC4GcsIxdJY:-MWkRtM0DdpA-WN7QqaC:b-5c21nu) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cpp_executor/Dockerfile#L98)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Your update looks good.


<!-- Sent from Reviewable.io -->

2021-03-29 13:17 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118)* status: 35 of 38 files reviewed, 7 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[components/cli_runner/README.md, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAf5ooE1XlfcRmhwBZ:-MWy7R7O-VY3A1GHF3cf:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/README.md#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Thinking about this more. How about we move `openmpf-docker/components/cli_runner/README.md` to the top level so it becomes `openmpf-docker/CLI_RUNNER.md`? 

Then add an brief "(Optional) CLI Runner" section to `openmpf-docker/README.md` underneath "(Optional) Docker Swarm Deployment" that links to `CLI_RUNNER.md`. Talk about the motivation and what it does. You can reuse this line:

> The OpenMPF Command Line Runner (CLI runner) allows users to run jobs with a single componen without the Workflow Manager.

The section will be similar in length to the "(Optional) Docker Swarm Deployment" section. Mention that it does not depend on a `docker-compose.yml` file and only runs one container by itself.

---

I know we have `README.md` files for the executors and things in their sub-directories. I think that's fine since developers will be diving down into the source code. Normal users may only look at what's at the top level. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 18:22 UTC, jrobble reviewed
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2021-03-30 18:04 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[components/cli_runner/Log4cxxConfig.xml, line 39 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MNAwqhyCg7Hn-Rj6b1g:-MWzZTzi0r6I6416SRhp:b-g3ya33) ([raw file](https://github.com/openmpf/openmpf-docker/blob/411b48f0fa220d432a966ad31259e883a47c0ee5/components/cli_runner/Log4cxxConfig.xml#L39)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

TODO: Try setting this and leaving it as default `INFO`.
</blockquote></details>

It might be worth providing an example to set the log level in `CLI_RUNNER.md`:

```
docker run --rm -e LOG_LEVEL=WARNING -i openmpf_keyword_tagging -t generic - < text.txt
```

---

We discussed this and decided against it for the sake of keeping the readme simple. The same env. var. works for Docker services.
___
*[CLI_RUNNER.md, line 23 at r7](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MWzUQHg510Pp_KzOf0M:-MWzUQHg510Pp_KzOf0N:b4ch4jm) ([raw file](https://github.com/openmpf/openmpf-docker/blob/f30d719f3646043d029cdbfbf24ebef0ba3ad70c/CLI_RUNNER.md#L23)):*
> ```Markdown
> `face.jpg` is a file on the host file system. It outputs the results to standard out.
> ```shell script
> docker run --rm -i openmpf_ocv_face_detection -t image - < face.jpg
> ```

This just hangs because no input image was piped in:

```
[mpf@openmpf-master openmpf-docker]$ docker run --rm -i openmpf_east_text_detection -t image -
Starting as component CLI runner...
INFO  [runner:237] - Loading descriptor from /opt/mpf/plugins/EastTextDetection/descriptor/descriptor.json
INFO  [east_component.py:43] - Creating instance of EastComponent
WARNING [runner:352] - Unable to determine mime type. Using the bogus mime type: image/octet-stream. To set it correctly add "-M MIME_TYPE=<actual mime type>" on the command line.
^C^C^C^C
```

I cannot ctrl-C out of this.

---

We discussed this and observed that this is only an issue with Python components. Due to how we're joining threads for C++ components, ctrl-C works. 

A user can simply use ctrl-D in the above example to exit out of the Python component process.
___
*[CLI_RUNNER.md, line 58 at r7](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MWzJ99l03tPUf5vOt9T:-MWzJ99mBAsek5CRmT1q:b-uuvl4u) ([raw file](https://github.com/openmpf/openmpf-docker/blob/f30d719f3646043d029cdbfbf24ebef0ba3ad70c/CLI_RUNNER.md#L58)):*
> ```Markdown
> property `FPS` to 29.97.
> ```shell script
> docker run --rm -i openmpf_ocv_face_detection -t image - -M FPS=29.97 < face.mp4
> ```

Change `-t image` to `-t video`.


<!-- Sent from Reviewable.io -->

2021-04-01 19:20 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118)* status: 34 of 38 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[CLI_RUNNER.md, line 58 at r7](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MWzJ99l03tPUf5vOt9T:-MXDot4F0fIaH_0p2VKH:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/f30d719f3646043d029cdbfbf24ebef0ba3ad70c/CLI_RUNNER.md#L58)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change `-t image` to `-t video`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-01 21:16 UTC, jrobble approved these changes
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[components/cli_runner/mpf_cli_runner.py, line 604 at r8](https://reviewable.io/reviews/openmpf/openmpf-docker/118#-MXEFn8p8K2bdRZhBIbu:-MXEFn8p8K2bdRZhBIbv:b4c9lyr) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c27e31dbddddd60b87855f7144d256a6c814af5c/components/cli_runner/mpf_cli_runner.py#L604)):*
> ```Python
>             existing_props[prop_key] = prop_val
> 
>     # CLI_RUNNER.md needs to be updated if any of these arguments or their descriptions change.
> ```

:thumbsup: 


<!-- Sent from Reviewable.io -->

2021-04-02 02:13 UTC, jrobble approved these changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2021-04-02 12:17 UTC, merged