Feat/optional build
openmpf/openmpf-docker pull request #222
Opened 2024-11-14 06:34 UTC by jrobble

**Issues:**

- https://github.com/openmpf/openmpf/issues/1 < Example
- https://github.com/openmpf/openmpf/issues/2 < Example

If a related issue doesn't exist, then create one first and assign it to yourself.

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/22 < Example
- https://github.com/openmpf/openmpf/pull/53 < Example

Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).

2024-11-18 12:31 UTC, brosenberg42 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/222)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`Jenkinsfile` line 363 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/222#-OBzEdTQ7dFYtXc2gCMb:-OBzEdTQ7dFYtXc2gCMc:bfeo4w) ([raw file](https://github.com/openmpf/openmpf-docker/blob/31aba28d9f2388ae9346c2a2f0ebafe20fd40446/Jenkinsfile#L363)):*
> ```Groovy
>                     customComponentServices.retainAll(keepServiceEntries.keySet())
>                     componentComposeYaml.services.clear()
>                     componentComposeYaml.services.putAll(keepServiceEntries)
> ```

I don't think you need `keepServiceEntries`. I think this is equivalent to:
```groovy
if (env.docker_services_to_build) {
    def searchImages = env.docker_services_to_build.split(',')
            .collect{ it.trim() }
    componentComposeYaml.services.keySet().retainAll(searchImages)
    customComponentServices.retainAll(componentComposeYaml.services.keySet())
}
```


<!-- Sent from Reviewable.io -->

2024-11-26 11:12 UTC, brosenberg42 approved these changes

2024-11-26 18:01 UTC, jrobble commented
*[`Jenkinsfile` line 363 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/222#-OBzEdTQ7dFYtXc2gCMb:-OCdcVG54c7M_mco6sRS:b1qtovk) ([raw file](https://github.com/openmpf/openmpf-docker/blob/31aba28d9f2388ae9346c2a2f0ebafe20fd40446/Jenkinsfile#L363)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't think you need `keepServiceEntries`. I think this is equivalent to:
```groovy
if (env.docker_services_to_build) {
    def searchImages = env.docker_services_to_build.split(',')
            .collect{ it.trim() }
    componentComposeYaml.services.keySet().retainAll(searchImages)
    customComponentServices.retainAll(componentComposeYaml.services.keySet())
}
```
</blockquote></details>

As discussed, `readYaml()` doesn't allow for this.


<!-- Sent from Reviewable.io -->

2024-11-26 18:02 UTC, jrobble reviewed
> Dismissed @brosenberg42 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/222)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2024-11-26 18:05 UTC, merged